### ISSUE TITLE
Feature request multiple geographies

### ISSUE THREAD

**Issue by emmaladolphi** [switchonproject/cids-custom-switchon#142]
The metadata wizard lacks an option to add datasets with multiple polygons/points/lines. Since external users cannot add multiple geographies the user has to make large bounding boxes (world boxes) over the area. This makes spatial search useless since you always get datasets with large boundning boxes.

Needed: a function to add multiple specific geographies in e.g. WKT format.

**Comment by emmaladolphi** [comment]
Some geography files are several hundred mb. See:
https://drive.google.com/file/d/0Bz-IvAiiqJRsanZHSVBKT3FtMWM/view?usp=sharing

**Comment by p-a-s-c-a-l** [comment]
This issue has already been discussed thoroughly in https://github.com/switchonproject/sip-html5/issues/46

Either you add distinct resources for each geography (recommended, see https://github.com/switchonproject/sip-html5/issues/46 for the limitations of the next approach), or you add one resource with **MULTIPOINT** or **MULTIPLOYGON** geography.

The later functionality is not supported by he wizard, since it involves also verification and probably post processing of the polygons by a database maintainer (we cannot allow end user to upload arbitrary WKT files via the Wizard that could interfere with spatial search) and possibly creating map layers on geoserver depending on the size of the **MULTIPOINT** or **MULTIPLOYGON**. If a user want to add such geographies, he has to get in contact with a system administrator.
